name: Playwright Tests on Windows

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  workflow_dispatch:  # Enables manual run from GitHub UI
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 12:00 AM UTC = 5:30 AM IST

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use your Node.js version here

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright Report
        if: always()  # Run this step even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
